runtime: python39
entrypoint: gunicorn -b :$PORT api_handlers:app

instance_class: F1

handlers:
- url: /.*
  script: auto

env_variables:
  CREDENTIALS: 'ml-model-read.json'
  BUCKET_NAME: 'optikoe-ml-models'
  MODEL_PATH: 'face_type_model.h5'