runtime: python39
service: api
entrypoint: gunicorn wsgi:application

instance_class: F4

handlers:
- url: /.*
  script: auto

env_variables:
  CREDENTIALS: 'ml-model-read.json'
  BUCKET_NAME: 'optikoe-ml-models'
  MODEL_PATH: 'face_type_model.h5'
  FLASK_ENV: 'production'
